### ISSUE TITLE
Cowboy typo causes a mismatch error.

### ISSUE THREAD

**Issue by codeadict** [peterholko/siege_perilous#22]
**rebar.conf** has a bad cowboy reference that causes a name_mismatch error, it says:

```erlang
 {cowbow, {git, "https://github.com/ninenines/cowboy"}},
```
when should be:

```erlang
 {cowboy, {git, "https://github.com/ninenines/cowboy"}},
```

**Comment by peterholko** [comment]
Fixed in https://github.com/peterholko/siege_perilous/commit/f3007aded607cdc7b8871595f13e655b2dfd5bce
